### ISSUE TITLE
configure error Vienna RNA library

### ISSUE THREAD

**Issue by CathyHao** [BackofenLab/IntaRNA#125]
I have installed the Vienna package in /home/haoyj/software/ViennaRNA-2.4.9Install sucessfully. 
The configure command for IntaRNA is:
./configure --prefix=/home/haoyj/software/intaRNA-2.2.0 --with-vrna=/home/haoyj/software/ViennaRNA-2.4.9Install --with-boost=/home/haoyj/software/boost_1_68_0
The error is next: I don't know why? Anyone can help me ?  Thanks a lot!!!!!
configure: check if VRNA version >= 2.4.4
checking for VRNA... no
configure: 
configure: The Vienna RNA C library version >= 2.4.4 is required.
configure:  -> It can be obtained from http://www.tbi.univie.ac.at/.
configure: 
configure:  -> Can't find the Vienna RNA library in given path '/home/haoyj/software/ViennaRNA-2.4.9Install'.
configure: 
configure: error: Some dependency was not met! See above for errors and relate to './configure --help'.

**Comment by martin-mann** [comment]
Hi @CathyHao 

we recently faced a similar error and it was due to a missing package. Please ensure you have `pkconfig` installled on your system (might require a reconfigure+make of the Vienna Package)

please test whether or not this solves the problem.

We plan a fix for the vienna package check in our configure for the next release.

Best,
Martin

**Comment by martin-mann** [comment]
https://en.wikipedia.org/wiki/Pkg-config

**Comment by martin-mann** [comment]
@CathyHao ... ?

**Comment by martin-mann** [comment]
seems the issue is resolved ...
