### ISSUE TITLE
ncRNA-NCBI prediction

### ISSUE THREAD

**Issue by rscotti** [BackofenLab/IntaRNA#171]
Hi, 

I have just installed locally on my HPC home space a copy of IntaRNA. I'd like to run a ncRNA-NCBI prediction using as target RNA sequences from prokaryotic NCBI Genome, locally using my IntaRNA installation. Is it possible? Can I use as target (-t) argument a bacterial genome downloaded from NCBI? 
Thanks

**Comment by martin-raden** [comment]
Hi @rscotti 
generally speaking: yes this is possible but you should be aware of some points:
- you can not use the `.gb` file from NCBI but have to extract the respective DNA sequence into proper FASTA format, which you can provide to the `-t` parameter
  - you can even gzip-compress the FASTA file and provide the compressed file to IntaRNA to reduce IO and drive space
- the precomputation of accessibility data for a large sequence will take a while; if you want to do multiple IntaRNA calls against the same genome, you might want to store the accessibility data gzipped and reload them from file the next time. check https://github.com/BackofenLab/IntaRNA#accFromFile and the example using the file `intarna.target.pu.gz`
- most likely you are only interested in some regions of your genome; either 
  - decompose the FASTA into the subsequences or
  - specifiy the (non-overlapping) regions of interest via `--tRegion`
  - e.g. if you want to emulate the predictions of the IntaRNA webserver, predictions would cover only -200/+100 around the start codon of each gene; I can provide a script for such a subsequence extraction if of interest
- to speedup on HPC, use 
  - multi-threading (either `--threads=0` for all CPUs or a respective number for the maximal thread count)
  - use automatic sequence decomposition and parallelization via `--windowWidth`; for instance setting `--windowWidth=2000 --windowOverlap=150` will chunk up your genome into windows of length 2000 that overlap in 150 nt (which is the default maximal interaction length; reduce if you set a lower `--tIntLenMax`)
- ensure you installed the recent version (>=3.1.0.2) since I did a couple of bugfixes
- depending on your ncRNAs of interest, I recommend additional seed constraint to further speedup and improve prediction results:
  - `--seedNoGU` will disable GU base pairs in seed
  - `--outNoGUend` will disable unstable GU base pairs at interaction and helix ends
  - `--outNoLP` will disable unstable non-stacked base pairs within the interaction
  - these and some other settings are enabled per default, when using the `IntaRNAsTar` [personality](https://github.com/BackofenLab/IntaRNA#intarnastar) by 
    - either directly calling `IntaRNAsTar` (installed symlink on IntaRNA)
    - or explicitely using the parameter `--personality=IntaRNAsTar`

so much for now... if I remember something else I will post here.. if this answers you question, feel free to close the issue.

Best,
Martin

**Comment by nongiga** [comment]
>   I can provide a script for such a subsequence extraction if of interest

Hi there, could you post the script for subsequence extraction please? I am interested at  searching for the target through a full genome

**Comment by martin-raden** [comment]
Hi @nongiga 
that would be the sequence extraction script from the CopraRNA package

https://github.com/PatrickRWright/CopraRNA/blob/master/coprarna_aux/parse_region_from_genome.pl

it is a Perl script which extracts from a Genbank file the subsequences of interest using the `BioPerl` package (which you have to install beside perl).

hope that helps.
best,
Martin
