### ISSUE TITLE
genome-wide sRNA target prediction

### ISSUE THREAD

**Issue by StephenLi55** [BackofenLab/IntaRNA#187]
Hi,

  I am trying to do a genome-wide target prediction for my sRNA sequence, by using the whole genome sequence as my target sequence. But I feel like it may not be the best approach as it is taking a long time to run, and also using the whole genome sequence is likely to perturb the predicted secondary structure of individual RNAs. Do you have other suggestions on running a genome-wide target prediction ? 

  The code I use is as followed :

 "~/miniconda3/bin/IntaRNA -q [the fasta file of my sRNA] -t [the fasta file of the whole genome sequence] --personality=IntaRNAsTar --threads 4 -n 100 --outMode C --out [the name of my output file]"

  best wishes,

  Stephen

**Comment by martin-raden** [comment]
Hi Stephen,

generally: if you have very long sequences, you might want to relate to [window-based](https://github.com/BackofenLab/IntaRNA#predWindowBased) computation, since the memory footprint will be much lower...

typically (afaik), sRNAs are interacting with mRNAs. thus, scanning against the whole genome sequence is most likely overkill.. that's why, eg the IntaRNA webserver only runs predictions around the start codon of each gene, considering genomic subsequence of eg from 200 up- to 100 downstream of the annotated start codon.

if you can extract the correct mRNA transcripts (ie you know transcription start and end for each gene), that would be the most valuable target data in my opinion. that way, you will not overestimate the 5' end of the mRNA, as it might happen when just taking 200 upstream of the start codon..

Does this already help?

Best,
Martin

**Comment by StephenLi55** [comment]
Hi Martin,

  That's really helpful. Thanks for the advice.

  best wishes,

  Stephen
________________________________

**Comment by martin-raden** [comment]
@StephenLi55 feel free to reopen the issue if you have further questions..
