### ISSUE TITLE
Reg: Prediction of miRNAs targets using 3' UTRs

### ISSUE THREAD

**Issue by harish0201** [BackofenLab/IntaRNA#196]
Hi,

Thank you for the wonderful tool! I'm currently going through the documentation, and since this is relatively a new domain for me, so I hope that I can raise some questions.

I'm working on a human cell-lines for which one of my colleagues predicted "novel" miRNAs using miRGe. Currently, one of the ways that I'm predicting the targets is to extract the 3' UTR regions of the genes and use them to compute the targets for the miRNAs. I have done the same using miranda and rnahybrid.

In case of IntaRNA, should I be using the srna or the duplex personality to predict the results? What are some sane settings that I can begin with so that I can understand IntaRNA better?

Is my approach still valid here, or do you suggest that I use the entire transcript sequences to predict the same?

Any help in this regard would be really helpful!

**Comment by martin-raden** [comment]
Hi @harish0201 

thanks for your questions, they are always welcome.

Generally, speaking: miRNAs are a bit special concerning constraints you can put, while IntaRNA (in its defaults) is tailored for small (s)RNAs (that are about 50-200nt long, so much longer than miRNAs.

The big strength of IntaRNA is its ability to take structuredness (here of miRNA targets) into account. This is disabled in the "IntaRNAduplex" personality, since it mimics a hybrid-only-prediction as the RNAduplex tool or similar approaches like RNAhybrid that you tested already. 
I wouldnt recommend for this setting, since 3' UTRs can and most likely will be structured to some extent, which influences what regions are accessible and likely for interaction formation.

IntaRNAsTar comes with optimized parameters for sRNA target prediction. So I would suggest this neither.

For miRNAs, you can
- specify the region where seeds are accepted eg to the first 10nt (5'-end) using eg `--seedQRange=1-10` (for query sequences)
- allow for bulges within the seed (which is disallowed in standard mode), eg `--seedMaxUP=1` (or 2; defaults to 0)

As you asked, you could consider to take also the end of the coding regions into the prediction (or even the whole transcipts) but forcing prediction therein to the 3' UTR using either --seedTRange or --tRegion. That way, accessibility predictions will be more reliable at the 5'-end of the 3' UTR (since no artificial sequence end is assumed).

Since you are not taking the whole target RNA into account (and your RNAs are rather long), I would use the (default) local accessibility computation, i.e. a window-based computation.

So much for now, hope it helps! :)

Best,
Martin
