### ISSUE TITLE
Vienna package not found

### ISSUE THREAD

**Issue by Cold7** [BackofenLab/IntaRNA#202]
Hi There.

While I was configuring  IntaRNA (using the command  `./configure --prefix=/shared/D2/opt`) I have the following error

```
checking for ANSI C header files... (cached) yes
configure: check if VRNA version >= 2.4.14
checking for VRNA... no
configure: 
configure: The Vienna RNA C library version >= 2.4.14 is required.
configure:  -> It can be obtained from http://www.tbi.univie.ac.at/.
configure: 
configure:  -> If installed in a non-standard path, please use '--with-vrna=PREFIX'.
configure: 
configure: error: Some dependency was not met! See above for errors and relate to './configure --help'
```

But I have the precompiled Vienna binary package installed (v2.5.0). I was looking for path where Vienna  was installed (because I just download the package and then install it through `sudo dpgk viennarna_2.5.0-1_amd64.deb`), locating executable files in `/us/bin`, while other files are in `/usr/share/ViennaRNA `

I have tried using both commands: `./configure --prefix=/shared/D2/opt --with-vrna=/usr/bin` and .`/configure --prefix=/shared/D2/opt --with-vrna=/usr/share/ViennaRNA` but the error persist. I have also tried using only `./configure `with no extra parameters

Can you help me to solve this problem, please

**Comment by martin-raden** [comment]
Hi @Cold7 
the problem is the missing pkgconfig library information of the installed ViennaRNA package.

Please use the `--disable-pkg-config` option in the `configure`call and it should work fine..

Best,
Martin

**Comment by Cold7** [comment]
Hi @martin-raden, thanks so much for your help. Unfortunately, adding the `--disable-pkg-config` flag did not resolve that problem, and the error message is still appearing. Should I reinstall Vienna from the non-precompiled version?

**Comment by martin-raden** [comment]
mhh.. the check is looking for the library headers etc. so `--with-vrna` should point to the folder that contains `include/ViennaRNA/vrna_config.h` and `lib/librna.a` (or .la). so this might be `--with-vrna=/usr/share/ViennaRNA` for you (but not sure.. please check for the location of the named files).

please check if this works:
```
configure --disable-pkg-config
```
or
```
configure --disable-pkg-config --with-vrna=/usr/share/ViennaRNA
```
using whatever path hosts the library headers and lib-files.

If that's not working you might have to relate to a local build of the vienna package. I havent tested building in debian systems, since I dont have access to them. alternatively, you might install the prebuild viennarna package via conda. with that, the above will work or you can directly install intarna via conda. ;)

**Comment by Cold7** [comment]
Hi again @martin-raden 

Thanks for your comments. I tried searching the above-mentioned files, but I was not able to locate the library. Finally, I have uninstalled the precompiled version and compiled it by myself and now it works, so I think that this can be marked as closed.

Thanks again for your help

Best,
Sebastian
