### ISSUE TITLE
IntaRNA1 bug in setting methods for ED values computation fixed?

### ISSUE THREAD

**Issue by michauhl** [BackofenLab/IntaRNA#34]
Setting the method for ED value computation (I think) did not work / was not sound in IntaRNA1, is this fixed?
Those were the parameters:
              -U               : use RNAup to compute ED values of binding RNA
                                 (default)
              -P               : use RNAplfold to compute ED values of target RNA
                                 (default)

**Comment by martin-mann** [comment]
per default, both RNAs are folded using `RNAplfold`.

if a folding/accessibility constraint is present, `RNAup` is used, since `RNAplfold` does not support constraints (as far as I found within the VRNA-lib).

thus, right now you **cannot explicitely** chose the used accessibility computation method.

do you think that's needed? For short RNA's or if folding window and base pair span is set to `0`, it makes no difference what tool is used.

**Comment by michauhl** [comment]
Okay so this is no issue anymore I see! :+1:  The parameter descriptions just did not make any sense in the old version (why should I set something that is already set)
