### ISSUE TITLE
Improve test cases

### ISSUE THREAD

**Issue by joachimwolff** [BackofenLab/IntaRNA#48]
The test cases do not cover everything.
- I have the issue that I know intaRNA is crashing somewhere and returns 'nothing' as an output but all test cases are passing.

**Comment by martin-mann** [comment]
IntaRNA catches all exceptions raised during computation.

In order to check for a bug during development you have to
- compile with debug information (to enable extended sanity checks)
- run `gdb src/bin/IntaRNA`
- add `catch throw` such that gdb stops when an exception is raised
- add `run YOURPARAMETERS` to start the computation that crashes
- add `bt` to backtrack the crash reason

and yes... the test cases do not cover everything (and will never do.. 😃 )
